name: WhatTheNickname
version: '1.0'
main: org.bindywashere.whatIsTheNickname.WhatIsTheNickname
api-version: '1.20'
commands:
  togglevisibility:
    description: Переключает видимость никнеймов
    usage: /togglevisibility [игрок]
    permission: hidenick.use
    permission-message: "У вас нет прав на выполнение этой команды!"
  setlanguage:
    description: Меняет язык плагина
    usage: /setlanguage <ru/en>
    permission: hidenick.admin
    permission-message: "У вас нет прав на выполнение этой команды!"
permissions:
  hidenick.use:
    description: Позволяет использовать togglevisibility
    default: op
  hidenick.admin:
    description: Позволяет менять язык плагина
    default: op
authors: [ bindyisreal ]
description: Hide nicknames